name: Deploy pygbag build to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pygbag
        run: pip install pygbag
      - name: Build web version
        run: pygbag --build .
      - name: Deploy to Pages
        uses: LucieTp/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
